backend:
  name: github
  repo: cfpb/design-system
  branch: master
  squash_merges: true
  commit_messages:
    create: Create “{{slug}}”
    update: Update “{{slug}}”
    delete: Delete “{{slug}}”

logo_url: https://cfpb.github.io/design-manual/static/img/logo/Logo0_@2.png
publish_mode: editorial_workflow
media_folder: docs/images/uploads
public_folder: /design-system/images/uploads

collections:
  - name: 'getting-started'
    label: 'Getting started pages'
    label_singular: 'Getting started page'
    folder: 'docs/getting-started/'
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'layout'
        value: 'variation'
        default: 'variation'
        widget: 'hidden'
      - name: 'section'
        default: 'getting-started'
        widget: 'hidden'
      - name: 'status'
        label: 'Implementation status'
        widget: 'select'
        required: false
        options:
          - label: 'Legacy'
            value: 'Legacy'
          - label: 'Proposed'
            value: 'Proposed'
          - label: 'Beta'
            value: 'Beta'
          - label: 'Released'
            value: 'Released'
      - name: 'description'
        label: 'Description'
        hint: 'If this page does not contain variations, you may leave the remaining fields blank, and the above field can be used for all page content.'
        widget: 'markdown'
      - name: 'variations'
        label: 'Variations'
        widget: 'list'
        fields:
          - name: 'variation_name'
            label: 'Variation name'
            widget: 'string'
          - name: 'variation_description'
            label: 'Variation description'
            widget: 'markdown'
            required: false
          - name: 'variation_code_snippet'
            label: 'HTML code snippet'
            widget: 'text'
          - name: 'variation_jinja_code_snippet'
            label: 'Jinja links or snippet'
            hint: 'Use this field to add links to Jinja2 templates in cfgov-refresh.'
            required: false
            widget: 'markdown'
          - name: 'variation_specs'
            label: 'Variation specifications'
            widget: 'markdown'
            required: false
      - name: 'usage'
        label: 'Usage'
        widget: 'markdown'
        required: false
      - name: 'accessibility'
        label: 'Accessibility'
        widget: 'markdown'
        required: false
      - name: 'research'
        label: 'Research'
        widget: 'markdown'
        required: false
      - name: 'related_items'
        label: 'Related items'
        widget: 'markdown'
        required: false
      - name: 'help_us'
        label: 'Help us make improvements'
        widget: 'markdown'
        required: false
  - name: 'foundation'
    label: 'Foundation pages'
    label_singular: 'Foundation page'
    folder: 'docs/foundation/'
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'layout'
        value: 'variation'
        default: 'variation'
        widget: 'hidden'
      - name: 'section'
        default: 'foundation'
        widget: 'hidden'
      - name: 'secondary_section'
        label: 'Navigation section'
        widget: 'select'
        required: false
        hint: 'Where on the website will this page live?'
        options:
          - label: 'Foundation > Design principles'
            value: 'Design principles'
          - label: 'Foundation > Identity'
            value: 'Identity'
          - label: 'Foundation > Imagery'
            value: 'Imagery'
          - label: 'Foundation > Multimedia'
            value: 'Multimedia'
      - name: 'status'
        label: 'Implementation status'
        widget: 'select'
        required: false
        options:
          - label: 'Legacy'
            value: 'Legacy'
          - label: 'Proposed'
            value: 'Proposed'
          - label: 'Beta'
            value: 'Beta'
          - label: 'Released'
            value: 'Released'
      - name: 'description'
        label: 'Description'
        hint: 'If this page does not contain variations, you may leave the remaining fields blank, and the above field can be used for all page content.'
        widget: 'markdown'
      - name: 'variations'
        label: 'Variations'
        widget: 'list'
        fields:
          - name: 'variation_name'
            label: 'Variation name'
            widget: 'string'
          - name: 'variation_description'
            label: 'Variation description'
            widget: 'markdown'
            required: false
          - name: 'variation_code_snippet'
            label: 'Variation code snippet'
            widget: 'text'
          - name: 'variation_jinja_code_snippet'
            label: 'Variation Jinja links or snippet'
            hint: 'Use this field to add links to Jinja2 templates in cfgov-refresh.'
            required: false
            widget: 'markdown'
          - name: 'variation_specs'
            label: 'Variation specifications'
            widget: 'markdown'
            required: false
      - name: 'usage'
        label: 'Usage'
        widget: 'markdown'
        required: false
      - name: 'accessibility'
        label: 'Accessibility'
        widget: 'markdown'
        required: false
      - name: 'research'
        label: 'Research'
        widget: 'markdown'
        required: false
      - name: 'related_items'
        label: 'Related items'
        widget: 'markdown'
        required: false
      - name: 'help_us'
        label: 'Help us make improvements'
        widget: 'markdown'
        required: false
  - name: 'components'
    label: 'Component pages'
    label_singular: 'Component page'
    folder: 'docs/components/'
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'layout'
        value: 'variation'
        default: 'variation'
        widget: 'hidden'
      - name: 'section'
        default: 'components'
        widget: 'hidden'
      - name: 'secondary_section'
        label: 'Navigation section'
        widget: 'select'
        required: false
        hint: 'Where on the website will this page live?'
        options:
          - label: 'Components > Alerts'
            value: 'Alerts'
          - label: 'Components > Content layouts'
            value: 'Content layouts'
          - label: 'Components > Data visualization'
            value: 'Data visualization'
          - label: 'Components > Forms'
            value: 'Forms'
          - label: 'Components > Navigation'
            value: 'Navigation'
          - label: 'Components > Tables'
            value: 'Tables'
          - label: 'Components > Text'
            value: 'Text'
      - name: 'status'
        label: 'Implementation status'
        widget: 'select'
        required: false
        options:
          - label: 'Legacy'
            value: 'Legacy'
          - label: 'Proposed'
            value: 'Proposed'
          - label: 'Beta'
            value: 'Beta'
          - label: 'Released'
            value: 'Released'
      - name: 'description'
        label: 'Description'
        hint: 'If this page does not contain variations, you may leave the remaining fields blank, and the above field can be used for all page content.'
        widget: 'markdown'
      - name: 'variations'
        label: 'Variations'
        widget: 'list'
        fields:
          - name: 'variation_name'
            label: 'Variation name'
            widget: 'string'
          - name: 'variation_description'
            label: 'Variation description'
            widget: 'markdown'
            required: false
          - name: 'variation_code_snippet'
            label: 'Variation code snippet'
            widget: 'text'
          - name: 'variation_jinja_code_snippet'
            label: 'Variation Jinja links or snippet'
            hint: 'Use this field to add links to Jinja2 templates in cfgov-refresh.'
            required: false
            widget: 'markdown'
          - name: 'variation_specs'
            label: 'Variation specifications'
            widget: 'markdown'
            required: false
      - name: 'usage'
        label: 'Usage'
        widget: 'markdown'
        required: false
      - name: 'accessibility'
        label: 'Accessibility'
        widget: 'markdown'
        required: false
      - name: 'research'
        label: 'Research'
        widget: 'markdown'
        required: false
      - name: 'related_items'
        label: 'Related items'
        widget: 'markdown'
        required: false
      - name: 'help_us'
        label: 'Help us make improvements'
        widget: 'markdown'
        required: false
  - name: 'templates'
    label: 'Templates pages'
    label_singular: 'Templates page'
    folder: 'docs/templates/'
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'layout'
        value: 'variation'
        default: 'variation'
        widget: 'hidden'
      - name: 'section'
        default: 'templates'
        widget: 'hidden'
      - name: 'secondary_section'
        label: 'Navigation section'
        widget: 'select'
        required: false
        hint: 'Where on the website will this page live?'
        options:
          - label: 'Templates > Web templates'
            value: 'Web templates'
          - label: 'Templates > Print templates'
            value: 'Print templates'
      - name: 'status'
        label: 'Implementation status'
        widget: 'select'
        required: false
        options:
          - label: 'Legacy'
            value: 'Legacy'
          - label: 'Proposed'
            value: 'Proposed'
          - label: 'Beta'
            value: 'Beta'
          - label: 'Released'
            value: 'Released'
      - name: 'description'
        label: 'Description'
        hint: 'If this page does not contain variations, you may leave the remaining fields blank, and the above field can be used for all page content.'
        widget: 'markdown'
      - name: 'variations'
        label: 'Variations'
        widget: 'list'
        fields:
          - name: 'variation_name'
            label: 'Variation name'
            widget: 'string'
          - name: 'variation_description'
            label: 'Variation description'
            widget: 'markdown'
            required: false
          - name: 'variation_code_snippet'
            label: 'Variation code snippet'
            widget: 'text'
          - name: 'variation_jinja_code_snippet'
            label: 'Variation Jinja links or snippet'
            hint: 'Use this field to add links to Jinja2 templates in cfgov-refresh.'
            required: false
            widget: 'markdown'
          - name: 'variation_specs'
            label: 'Variation specifications'
            widget: 'markdown'
            required: false
      - name: 'usage'
        label: 'Usage'
        widget: 'markdown'
        required: false
      - name: 'accessibility'
        label: 'Accessibility'
        widget: 'markdown'
        required: false
      - name: 'research'
        label: 'Research'
        widget: 'markdown'
        required: false
      - name: 'related_items'
        label: 'Related items'
        widget: 'markdown'
        required: false
      - name: 'help_us'
        label: 'Help us make improvements'
        widget: 'markdown'
        required: false
