# Redirects
plugins:
  - jekyll-redirect-from

# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "src", "node_modules"]
markdown: kramdown
highlighter: rouge

# Organization
org: CFPB
description: CFPB's design system
repository: test-things/design-system

# Title
title: Design System
name: Design System

# Logo
logourl: assets/img/cfpb-logo.png
logoalt: Consumer Financial Protection Bureau

# We currently don't use this in the templates
subtitle: A set of principles and standards for the Consumer Financial Protection Bureau's design projects.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/design-system'
