name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install Bundler
      run: gem install bundler

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install dependencies with Yarn
      run: yarn

    - name: Run unit tests
      run: yarn test

  browser-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set up Ruby for Jekyll
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install dependencies with Yarn
      run: yarn

    - name: Start local Design System website server
      run: |
        yarn start &
        sleep 5

    - name: Run browser tests
      # Don't run these tests on forks. It would be nice to instead check
      # to see if the Sauce Labs environment variables are defined, but that
      # doesn't seem currently possible:
      # https://github.com/actions/runner/issues/520
      if: ${{ github.repository_owner == 'cfpb' }}
      env:
        # These credentials are from @contolini's CFPB Sauce Labs account
        # They're defined on the repo's settings page:
        # https://github.com/cfpb/design-system/settings/secrets
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: yarn test:browser:cloud
