apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 15
  sauceignore: .sauceignore
cypress:
  configFile: cypress.config.js
  version: 13.6.0
  record: false
  key: ''
  reporters: []
suites:
  - name: cypress - Windows 10 - chrome
    browser: 'chrome'
    browserVersion: 'latest'
    platformName: 'Windows 10'
    config:
      testingType: e2e
      specPattern:
        - 'test/cypress/e2e/**/*.cy.js'
      # Increase the VM's resolution for Netlify CMS tests that require a wider viewport.
      screenResolution: '1920x1200'
  - name: cypress - Windows 11 - edge
    browser: 'microsoftedge'
    browserVersion: 'latest'
    platformName: 'Windows 11'
    config:
      testingType: e2e
      specPattern:
        - 'test/cypress/e2e/**/*.cy.js'
      screenResolution: '1920x1200'
      exclude:
        # Netlify CMS is only tested with Chrome
        - 'test/cypress/e2e/docs/netlify-cms.cy.js'
  - name: cypress - Windows 10 - firefox
    browser: 'firefox'
    browserVersion: 'latest'
    platformName: 'Windows 10'
    config:
      testingType: e2e
      specPattern:
        - 'test/cypress/e2e/**/*.cy.js'
      screenResolution: '1920x1200'
      exclude:
        # Netlify CMS is only tested with Chrome
        - 'test/cypress/e2e/docs/netlify-cms.cy.js'
rootDir: .
